---
title: "R Notebook"
output: html_notebook
---
#clear all objects
```{r}
rm(list=ls())
```
#create dataframe with values as iris
```{r}
iris_diff_colnames = data.frame(iris)
iris_diff_colnames
```
#change column names of iris_diff_colnames
```{r}
colnames(iris_diff_colnames) = c("col1_seplen","col2_sepwid","col3_petlen","col4_petwid")
iris_diff_colnames
```
#create dataframe mtcars_df with mgp, disp, wt as the 3 columns of df
```{r}
mtcars_df = mtcars[,c(1,3,6)]
mtcars_df
```

#create Scatter plot for speed, dist in cars
```{r}
plot(cars$speed,cars$dist)
```
#create dummy dataframe having employee detils (min 10rows)
```{r}
Employee = c("John","Siri","Hans","Sonal","Albert","Jeremy","Erwin","Mike", "Ester", "Micheal","Paul")
Salary = c(3000,4000,4600,3200,5000,4200,3800,5300,6000,4900,5500)
Age = c(35, 40, 53, 38, 59, 27, 24, 42, 51, 48, 52)
Start_date = c("21-7-2010","7-7-2011","30-11-2005","30-5-2015","1-1-2013","5-10-1999","5-6-2017","3-9-1998","7-3-2012","3-11-1993","20-10-2010")
Employee_data = data.frame(Employee,Salary,Age,Start_date, stringsAsFactors = F)
```
#View Employee_data 
```{r}
Employee_data
```

